### ISSUE TITLE
Upload Examples

### ISSUE THREAD

**Issue by konstantin-yakovlev** [PathPlanning/AStar-JPS-ThetaStar#8]
We need to create 'examples' folder and upload some sample tasks into it/

**Comment by Have3306** [comment]
i can't load xml, once the exe running ,it will put error. so how do i do, if i want load the xml safely...

**Comment by Have3306** [comment]
in map.cpp line69, its a Infinite loop maybe? and run on debug at 8th ,it put a problem about out of memory??

**Comment by aandreychuk** [comment]
@Have3306 if you mean line 69 in current map.cpp file which is `std::transform(value.begin(),value.end(), value.begin(), ::tolower);`, then it's perfectly OK and there is no an infinite loop. For better looking it's probably good to add `std` near `::tolower`, but it changes nothing for compilation.
I have checked one more time and haven't found any problems with debug build. By the truth, there is no any special code for debug at all :).
