### ISSUE TITLE
Error! Pathfinding task file (XML) is not specified!

### ISSUE THREAD

**Issue by babyfucker** [PathPlanning/AStar-JPS-ThetaStar#9]
I got crashed when I execute the ASearch in terminal with "./ASearch -../build-ASearch-Desktop_Qt_5_8_0_clang_64bit-Debug/example.xml",is that correct? THANKS!

**Comment by aandreychuk** [comment]
Yes, that's right. XML-file should be an input parameter. If it is in the same directory as the executable file, it is enough to write only name of the file, like "asearch example.xml".
And it's better to make release-build.

**Comment by babyfucker** [comment]
It works with"./ASearch example.xml",but I got a new problem "Segmentation fault: 11". it seems out of memory

**Comment by aandreychuk** [comment]
I have built the current source files in Ubuntu 15.04 with Qt 5.8+GCC and clang 3.6 and haven't found any problems...
Build in Windows using MinGW is also works fine.
